/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dcaa_registrar2;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author GOD
 */



public class Add_Records extends javax.swing.JFrame {

    /**
     * Creates new form Add_Students_Records
     */
    
     DefaultListModel model = new DefaultListModel();
    String filepath;
    public Add_Records() {
        initComponents();
        schoolyear2();
        menu.add(panel);
        StudentTable();
        StudentCombo();
        AutoCompleteComboBox();
        tableEditFormat();
 
    }

    
    
    
    
    
       
    public class student
            
    {
        
        
        int id;
        
        String name;
        
        
        public student (int id, String name)
        {
            
            this.id = id;
            this.name= name;
            
            
        }

        @Override
        public String toString()
        {
            
            return name;
            
        } 
    }

    
     public class SchoolYear2 
       {
           int id;
           String name;
           public SchoolYear2 (int id, String name)
           {     
               this.id=id;
               this.name=name;     
           }
           @Override
           public String toString ()
           {   
               return name;  
            }
       }
    
    
    Connection Mycon;
    ResultSet rs;

       public void en()
       
       {
        
           
        JFileChooser jfchoose = new JFileChooser();
        jfchoose.showOpenDialog(this);
        

        
        try {
            
            //File file= new File("your_path");
            
            File file= jfchoose.getSelectedFile();
            FileInputStream enroll= new FileInputStream(file); // para sa prepared statement
          //  filepath = file.getAbsolutePath();
            ENROLLMENT.setText(enroll.toString());
 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Add_Records.class.getName()).log(Level.SEVERE, null, ex);
        }

       }
       
       
       
            public void LoadSearchData(){

         
             
              try {
               String name="%"+this.search.getText()+"%";
             
                 
                DefaultTableModel model =  (DefaultTableModel)jTable.getModel() ;
                 int col;
                Class.forName("com.mysql.cj.jdbc.Driver");
               Mycon=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dcaa_registrar","root","root");   
               PreparedStatement ps;
               ps = Mycon.prepareStatement("select * from enrolled_students where fullname LIKE '"+name+"'"); 

             ResultSet rs= ps.executeQuery();
             
               
           model.setRowCount(0);
                         while(rs.next()){   
                             
                             //number sa mga columns sa imohang tables
                        model.addRow(new Object[]{rs.getString(6)});
    
      
    
                                }  
             
            }catch (ClassNotFoundException | SQLException  ex) {
                 JOptionPane.showMessageDialog(this, ex,"ERROR", JOptionPane.ERROR_MESSAGE);
            }         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        menu = new javax.swing.JPopupMenu();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PSA = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        enrollment = new javax.swing.JButton();
        ENROLLMENT = new javax.swing.JTextField();
        enrool = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        GOODMORAL = new javax.swing.JTextField();
        goodmoral1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        COMPLETION = new javax.swing.JTextField();
        completion = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        DISMISSAL = new javax.swing.JTextField();
        dismissal = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        SF10 = new javax.swing.JTextField();
        sf10 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        SF9 = new javax.swing.JTextField();
        sf9 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        PSA1 = new javax.swing.JTextField();
        psa = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        diploma = new javax.swing.JButton();
        DIPLOMA = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        SAVE = new javax.swing.JButton();
        TRYSAVE = new javax.swing.JButton();
        CLEAR1 = new javax.swing.JButton();
        CLEAR4 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        students1 = new javax.swing.JComboBox();
        schoolyr = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jPanel5.setBackground(new java.awt.Color(43, 70, 60));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("All Rights Reserved 2020");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(244, 241, 233));

        PSA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        PSA.setForeground(new java.awt.Color(43, 70, 60));
        PSA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        enrollment.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        enrollment.setForeground(new java.awt.Color(204, 0, 0));
        enrollment.setText("Attach File");
        enrollment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        enrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentActionPerformed(evt);
            }
        });

        enrool.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        enrool.setForeground(new java.awt.Color(204, 0, 0));
        enrool.setText("sulod");
        enrool.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        enrool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enroolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(ENROLLMENT, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enrool, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(enrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(enrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ENROLLMENT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrool, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        PSA.addTab("Certification of Enrollment", jPanel3);

        goodmoral1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        goodmoral1.setForeground(new java.awt.Color(204, 0, 0));
        goodmoral1.setText("Attach File");
        goodmoral1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        goodmoral1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodmoral1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(GOODMORAL, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goodmoral1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GOODMORAL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goodmoral1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        PSA.addTab("Certificate of Good Moral", jPanel4);

        completion.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        completion.setForeground(new java.awt.Color(204, 0, 0));
        completion.setText("Attach File");
        completion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        completion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(COMPLETION, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(completion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(COMPLETION, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(completion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        PSA.addTab("Certificate of Completion", jPanel2);

        dismissal.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        dismissal.setForeground(new java.awt.Color(204, 0, 0));
        dismissal.setText("Attach File");
        dismissal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        dismissal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismissalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(DISMISSAL, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dismissal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DISMISSAL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dismissal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        PSA.addTab("Certiciation of Honorable Dismissal", jPanel6);

        sf10.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        sf10.setForeground(new java.awt.Color(204, 0, 0));
        sf10.setText("Attach File");
        sf10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        sf10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sf10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(SF10, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sf10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SF10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sf10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        PSA.addTab("SF 10", jPanel7);

        sf9.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        sf9.setForeground(new java.awt.Color(204, 0, 0));
        sf9.setText("Attach File");
        sf9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        sf9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sf9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(SF9, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sf9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SF9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sf9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        PSA.addTab("SF 9", jPanel8);

        psa.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        psa.setForeground(new java.awt.Color(204, 0, 0));
        psa.setText("Attach File");
        psa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        psa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(PSA1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PSA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        PSA.addTab("PSA", jPanel9);

        diploma.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        diploma.setForeground(new java.awt.Color(204, 0, 0));
        diploma.setText("Attach File");
        diploma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        diploma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diplomaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(DIPLOMA, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diploma, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DIPLOMA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diploma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        PSA.addTab("Diploma", jPanel10);

        jPanel11.setBackground(new java.awt.Color(244, 241, 233));
        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SAVE.setBackground(new java.awt.Color(51, 51, 51));
        SAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/ADD/default.png"))); // NOI18N
        SAVE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(104, 143, 78), 2));
        SAVE.setFocusPainted(false);
        SAVE.setRolloverEnabled(true);
        SAVE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/ADD/hover.png"))); // NOI18N
        SAVE.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/ADD/hover.png"))); // NOI18N
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        TRYSAVE.setBackground(new java.awt.Color(51, 51, 51));
        TRYSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/EDIT/default.png"))); // NOI18N
        TRYSAVE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(104, 143, 78), 2));
        TRYSAVE.setFocusPainted(false);
        TRYSAVE.setRolloverEnabled(true);
        TRYSAVE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/EDIT/hover.png"))); // NOI18N
        TRYSAVE.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/EDIT/hover.png"))); // NOI18N
        TRYSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRYSAVEActionPerformed(evt);
            }
        });

        CLEAR1.setBackground(new java.awt.Color(51, 51, 51));
        CLEAR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/CLEAR/default.png"))); // NOI18N
        CLEAR1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(104, 143, 78), 2));
        CLEAR1.setFocusPainted(false);
        CLEAR1.setRolloverEnabled(true);
        CLEAR1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/CLEAR/hover.png"))); // NOI18N
        CLEAR1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/CLEAR/hover.png"))); // NOI18N
        CLEAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEAR1ActionPerformed(evt);
            }
        });

        CLEAR4.setBackground(new java.awt.Color(51, 51, 51));
        CLEAR4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/EDIT/default.png"))); // NOI18N
        CLEAR4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(104, 143, 78), 2));
        CLEAR4.setFocusPainted(false);
        CLEAR4.setRolloverEnabled(true);
        CLEAR4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/EDIT/hover.png"))); // NOI18N
        CLEAR4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/EDIT/hover.png"))); // NOI18N
        CLEAR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEAR4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CLEAR4)
                    .addComponent(CLEAR1)
                    .addComponent(TRYSAVE)
                    .addComponent(SAVE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TRYSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CLEAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CLEAR4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel12.setBackground(new java.awt.Color(244, 241, 233));
        jPanel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(56, 74, 19));
        jLabel17.setText("Student's Name :");

        students1.setBackground(new java.awt.Color(244, 241, 233));
        students1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        students1.setForeground(new java.awt.Color(165, 19, 29));
        students1.setFocusable(false);
        students1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                students1MouseClicked(evt);
            }
        });
        students1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                students1KeyPressed(evt);
            }
        });

        schoolyr.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(56, 74, 19));
        jLabel18.setText("School Year :");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schoolyr, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(students1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(students1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schoolyr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel13.setBackground(new java.awt.Color(43, 70, 60));

        search.setAutoscrolls(false);
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search.setFocusCycleRoot(true);
        search.setFocusTraversalPolicyProvider(true);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(203, 220, 139));
        jLabel1.setText("Search :");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jScrollPane2.setBackground(new java.awt.Color(244, 241, 233));

        jTable.setBackground(new java.awt.Color(244, 241, 233));
        jTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable.setForeground(new java.awt.Color(43, 70, 60));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student's Name"
            }
        ));
        jTable.setFocusable(false);
        jTable.setRowHeight(25);
        jTable.setSelectionBackground(new java.awt.Color(43, 70, 60));
        jTable.setSelectionForeground(new java.awt.Color(244, 241, 233));
        jTable.setShowVerticalLines(false);
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PSA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(PSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
     private void tableEditFormat()
       {
           
            
                                                jTable.getTableHeader().setFont(new Font("Segui UI", Font.BOLD,20));
                                                jTable.getTableHeader().setOpaque(false);
                                                jTable.getTableHeader().setBackground(new Color(165,19,29));
                                                jTable.getTableHeader().setForeground(new Color(255,255,255));
                                                jTable.getRowHeight(20);
                                                
                                                DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
                                                
                                                
                                                rightRenderer.setHorizontalAlignment(JLabel.CENTER);
                                                
                                               
       }
    
    
    
      private void AutoCompleteComboBox(){          
          AutoCompleteDecorator.decorate(students1);
    }
     
     private void schoolyear2()
        {
             try {

                Class.forName("com.mysql.cj.jdbc.Driver");
            Mycon=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dcaa_registrar","root","root");   
                PreparedStatement ps;
                ps=Mycon.prepareStatement("select * from school_year");
                rs= ps.executeQuery();
                schoolyr.removeAllItems();
                while (rs.next())
                {             
                     schoolyr.addItem(new SchoolYear2(rs.getInt(1),rs.getString(2)));             
                }
            }catch (ClassNotFoundException | SQLException  ex) {
                  JOptionPane.showMessageDialog(this, ex,"ERROR", JOptionPane.ERROR_MESSAGE);
            }
  
        }
    
    private void StudentTable()
    
    {
        
        int c;
           try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                Mycon=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dcaa_registrar","root","root");   
                PreparedStatement ps;
                ps=Mycon.prepareStatement("select * from enrolled_students");
                rs= ps.executeQuery();
                
                DefaultTableModel modelt = (DefaultTableModel)jTable.getModel();
                ResultSetMetaData rsd=rs.getMetaData();
                   c = rsd.getColumnCount(); 
                
                     modelt.setRowCount(0);

                
                                    while (rs.next()) 
                                                {          
                                                    Vector v = new Vector();
                                                    
                                                    for (int i = 0; i <= 35; i++) 
                                                    { 
                                                         //v.add(rs.getString("id")); 
                                                           
                                                        v.add(new student(rs.getInt(1), rs.getString(6)));
                                                    }
                                                    
                                                    modelt.addRow(v); 
                                                   
                                                }        
            }catch (ClassNotFoundException | SQLException  ex) {
                JOptionPane.showMessageDialog(this, ex,"ERROR", JOptionPane.ERROR_MESSAGE);
            }

    }
    
    
     private void StudentCombo()
    
    {
        
        int c;
           try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                Mycon=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dcaa_registrar","root","root");   
                PreparedStatement ps;
                ps=Mycon.prepareStatement("select * from enrolled_students");
                rs= ps.executeQuery();
                
              
                ResultSetMetaData rsd=rs.getMetaData();
                   c = rsd.getColumnCount(); 
                
                    
                while (rs.next())
                
                {
                    
                
                    
                    students1.addItem(new student(rs.getInt(1), rs.getString(6)));

                }
                
                           
               
               
            }catch (ClassNotFoundException | SQLException  ex) {
                 JOptionPane.showMessageDialog(this, ex,"ERROR", JOptionPane.ERROR_MESSAGE);
            }

            
        
        
    }
    
     
    
public boolean verifyText()
    {
        
        if (schoolyr.getSelectedItem().equals("") || students1.getSelectedItem().toString().equals("") || ENROLLMENT.getText().equals("") || DISMISSAL.getText().equals("") || GOODMORAL.getText().equals("")    || COMPLETION.getText().equals("") ||  SF10.getText().equals("") ||  SF9.getText().equals("") ||  DIPLOMA.getText().equals("") ||  PSA1.getText().equals(""))

          {
            JOptionPane.showMessageDialog(this," Failed...!!! One or More Empty");
            return false;
       
        } else {
             return true;
        }
     
     
        
    }
    
     
    
     private void pop(){
        
       
          menu.show(search, 0, search.getHeight());
        
    }
    
    private void click(){

        JPopupMenu menu1 = this.menu;
        
        menu1.setVisible(false);
    }
    
    
    
    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        
//            String sc= SCHOOLYEAR.getText();
//            String grade = GRADEENROLLED.getText();
//            String track = TRACKENROLLED.getText();
//            String sa = STUDENT_ACCOUNT_NUMBER.getText();
//            String lrn = LRN.getText();

         // SchoolYear2 sy = (SchoolYear2)schoolyr.getSelectedItem();
         
         //    student s = (student)STUDENT_NAME.getText();
         //String sn = STUDENT_NAME.getText();
//            String gender = GENDER.getText();
         //String name= ENROLLMENT.getText().toString();
         
         
        SchoolYear2 sy = (SchoolYear2)schoolyr.getSelectedItem(); 
        student studentmame = (student)students1.getSelectedItem();
         
         
        //String enr= ENROLLMENT.get           
        String good= GOODMORAL.getText();
        String com= COMPLETION.getText();
        String dis= DISMISSAL.getText();
        String sf= SF10.getText();
        String sff= SF9.getText();
        String pss= PSA1.getText();
        String dip= DIPLOMA.getText();
            
        DateTimeFormatter dtf= DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now= LocalDateTime.now();
        String timestamp = dtf.format(now);
    
        Path pat = Paths.get(ENROLLMENT.getText());
        
       

         try {   
             
          byte[] fileContent = Files.readAllBytes(pat);
          ByteArrayInputStream bias = new ByteArrayInputStream(fileContent);
          File pdf = new File(ENROLLMENT.getText());
          FileInputStream FileInput = new FileInputStream(pdf);        
          ByteArrayOutputStream bos = new ByteArrayOutputStream();
          
             
        Class.forName("com.mysql.cj.jdbc.Driver");
        Mycon=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dcaa_registrar","root","root");
        PreparedStatement ps;
       
        ps=Mycon.prepareStatement("INSERT INTO student_records ( school_year_id, enrolled_students_id, crt_enrollment, crt_goodmoral, crt_completion, honorable_dismissal, sf10, sf9, psa, diploma, timestamp) VALUES (?,?,?,?,?,?,?,?,?,?,?)");
        
         ps.setInt(1,  sy.id);
       ps.setInt(2,  studentmame.id);
        ps.setBlob(3, bias);  
        ps.setString(4, good);
        ps.setString(5, com);
        ps.setString(6, dis);
        ps.setString(7, sf);
        ps.setString(8, sff);
        ps.setString(9, pss);
        ps.setString(10, dip);
        ps.setString(11, timestamp);
        
//        String sql = "INSERT INTO testtable(stringcolumn, blobcolumn) VALUES(?,?)";
//
//        PreparedStatement statement = conn.getConnection().prepareStatement(sql);
//        statement.setLong(1, version);
//        ByteArrayInputStream bais = new ByteArrayInputStream(getByteArrayFromFile(document));
//        statement.setBlob(2, bais);          
//        statement.execute();
        
        
        

        ps.execute();      

                    JOptionPane.showMessageDialog(null, "Student Successfully Enrolled");
                    
                    // schoolyr.setSelectedIndex(-1);
                     students1.setSelectedIndex(-1);
                     ENROLLMENT.setText("");
                     GOODMORAL.setText("");
                     COMPLETION.setText("");
                     DISMISSAL.setText("");
                     SF10.setText("");
                     SF9.setText("");
                     PSA1.setText("");
                     DIPLOMA.setText("");
                    
                    
                // DESKTOP.schoolyear.setText(jComboBox1.getSelectedItem().toString());
               
         } catch (ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex,"ERROR",  JOptionPane.ERROR_MESSAGE);
                     Logger.getLogger(table_suggetions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
             Logger.getLogger(Add_Records.class.getName()).log(Level.SEVERE, null, ex);
         }
            
    }//GEN-LAST:event_SAVEActionPerformed

    private void enrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentActionPerformed
        
        JFileChooser jfchoose = new JFileChooser();
        jfchoose.showOpenDialog(this);
                       
        try {
            
        File f =  jfchoose.getSelectedFile();
        

         filepath = f.getAbsolutePath();
       // filepath = filepath.replace('\\', '/');
        ENROLLMENT.setText(filepath);
            
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, "Error");
        }
        
        
    }//GEN-LAST:event_enrollmentActionPerformed

     @SuppressWarnings("empty-statement")
    private void enroolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enroolActionPerformed

        
      

         
             
        byte[] photo=null;
        String filename=null;
        
        
        JFileChooser jfchoose = new JFileChooser();
        jfchoose.showOpenDialog(this);
        File f =  jfchoose.getSelectedFile();
        filename=f.getAbsolutePath();
              filepath = f.getAbsolutePath();
              filepath = filepath.replace('\\', '/');
              ENROLLMENT.setText(filepath);
             
//          byte[] fileContent = Files.readAllBytes(pat);
//          ByteArrayInputStream bias = new ByteArrayInputStream(fileContent);
//          File pdf = new File(ENROLLMENT.getText());
//          FileInputStream FileInput = new FileInputStream(pdf);        
//          ByteArrayOutputStream bos = new ByteArrayOutputStream();
          
             
       
//        try {
//
//        File f =  jfchoose.getSelectedFile();
//
//        //filepath = f.getName();
//         filepath = f.getAbsolutePath();
//        filepath = filepath.replace('\\', '/');
//        GOODMORAL.setText(filepath);
//
//
//        } catch (Exception e) {
//
//             JOptionPane.showMessageDialog(this, e,"ERROR", JOptionPane.ERROR_MESSAGE);
//        }
//
//        try {
//
//        File pdf = new File(filename);
//        FileInputStream FileInput = new FileInputStream(pdf);
//       // ByteArrayOutputStream bos = new ByteArrayOutputStream();
//
//       byte [] buf = new byte[1024];
//        ByteArrayInputStream bias = new ByteArrayInputStream(FileInput);
//
//
//
//
//
//            for (int readNum; (readNum=FileInput.read(buf))!=1;) {
//
//
//
//                bias.write(buf, 0, readNum);
//
//
//            }
//
//        photo=bias.toByteArray();
//
//        } catch (IOException e) {
//        }
         
            
              
             
              
        
          
          
//        try {
//            
//        File f =  jfchoose.getSelectedFile();
//        
//        //filepath = f.getName();
//         filepath = f.getAbsolutePath();
//        filepath = filepath.replace('\\', '/');
//        GOODMORAL.setText(filepath);
//            
//            
//        } catch (Exception e) {
//            
//             JOptionPane.showMessageDialog(this, e,"ERROR", JOptionPane.ERROR_MESSAGE);
//        }
              

//
//        try {
//            
//        File pdf = new File(filename);
//        FileInputStream FileInput = new FileInputStream(pdf);
//       // ByteArrayOutputStream bos = new ByteArrayOutputStream();
//       
//       byte [] buf = new byte[1024];
//        ByteArrayInputStream bias = new ByteArrayInputStream(FileInput);
//        
//        
//        
//        
//        
//            for (int readNum; (readNum=FileInput.read(buf))!=1;) {
//                
//                
//                
//                bias.write(buf, 0, readNum);
//                
//                
//            }
//                    
//        photo=bias.toByteArray();
//                    
//        } catch (IOException e) {
//        }
              
    }//GEN-LAST:event_enroolActionPerformed

    
    private void completionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completionActionPerformed
        JFileChooser jfchoose = new JFileChooser();
        jfchoose.showOpenDialog(this);
        
        
        try {
            
        File f =  jfchoose.getSelectedFile();
        //filepath = f.getName();
         filepath = f.getAbsolutePath();
        filepath = filepath.replace('\\', '/');
        COMPLETION.setText(filepath);
            
            
        } catch (Exception e) {
            
             JOptionPane.showMessageDialog(this, e,"ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_completionActionPerformed

    private void dismissalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissalActionPerformed
        JFileChooser jfchoose = new JFileChooser();
        jfchoose.showOpenDialog(this);
        
        
        try {
            
        File f =  jfchoose.getSelectedFile();
        //filepath = f.getName();
         filepath = f.getAbsolutePath();
        filepath = filepath.replace('\\', '/');
        DISMISSAL.setText(filepath);
            
            
        } catch (Exception e) {
            
             JOptionPane.showMessageDialog(this, e,"ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_dismissalActionPerformed

    private void sf10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sf10ActionPerformed
          JFileChooser jfchoose = new JFileChooser();
        jfchoose.showOpenDialog(this);
        
        
        try {
            
        File f =  jfchoose.getSelectedFile();
        //filepath = f.getName();
         filepath = f.getAbsolutePath();
        filepath = filepath.replace('\\', '/');
        SF10.setText(filepath);
            
            
        } catch (Exception e) {
            
             JOptionPane.showMessageDialog(this, e,"ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sf10ActionPerformed

    private void sf9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sf9ActionPerformed
           JFileChooser jfchoose = new JFileChooser();
        jfchoose.showOpenDialog(this);
        
        
        try {
            
        File f =  jfchoose.getSelectedFile();
        //filepath = f.getName();
         filepath = f.getAbsolutePath();
        filepath = filepath.replace('\\', '/');
        SF9.setText(filepath);
            
            
        } catch (Exception e) {
            
             JOptionPane.showMessageDialog(this, e,"ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sf9ActionPerformed

    private void psaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psaActionPerformed
           JFileChooser jfchoose = new JFileChooser();
        jfchoose.showOpenDialog(this);
        
        
        try {
            
        File f =  jfchoose.getSelectedFile();
        //filepath = f.getName();
         filepath = f.getAbsolutePath();
        filepath = filepath.replace('\\', '/');
        PSA1.setText(filepath);
            
            
        } catch (Exception e) {
            
             JOptionPane.showMessageDialog(this, e,"ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_psaActionPerformed

    private void diplomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diplomaActionPerformed
           JFileChooser jfchoose = new JFileChooser();
        jfchoose.showOpenDialog(this);
        
        
        try {
            
        File f =  jfchoose.getSelectedFile();
        //filepath = f.getName();
         filepath = f.getAbsolutePath();
        filepath = filepath.replace('\\', '/');
        DIPLOMA.setText(filepath);
            
            
        } catch (Exception e) {
            
             JOptionPane.showMessageDialog(this, e,"ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_diplomaActionPerformed

    private void TRYSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRYSAVEActionPerformed
      
        
         File f = new File("D:/USERSsdasda/Documents/debussyclairdelune.pdf");
        
        try{
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        Mycon=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dcaa_registrar","root","root");
        PreparedStatement ps;
       
       // ps=Mycon.prepareStatement("INSERT INTO student_records ( school_year_id, enrolled_students_id, crt_enrollment, crt_goodmoral, crt_completion, honorable_dismissal, sf10, sf9, psa, diploma, timestamp) VALUES (?,?,?,?,?,?,?,?,?,?,?)");
       ps = Mycon.prepareStatement("INSERT INTO insertfilesample ( name, file values (?,?)");
       
       ps.setString(1, f.getName());
      
        
       FileInputStream  fileInputStream = new FileInputStream(f);
        ps.setBinaryStream(2, fileInputStream, fileInputStream.available());
       
        
//        String sql = "INSERT INTO testtable(stringcolumn, blobcolumn) VALUES(?,?)";
//
//        PreparedStatement statement = conn.getConnection().prepareStatement(sql);
//        statement.setLong(1, version);
//        ByteArrayInputStream bais = new ByteArrayInputStream(getByteArrayFromFile(document));
//        statement.setBlob(2, bais);          
//        statement.execute();
        
        
        

        ps.executeUpdate();      

                    JOptionPane.showMessageDialog(null, "Bright Ka");
                    
                    // schoolyr.setSelectedIndex(-1);
            
                    
                    
                // DESKTOP.schoolyear.setText(jComboBox1.getSelectedItem().toString());
               
         }catch (ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex,"ERROR",  JOptionPane.ERROR_MESSAGE);
                     Logger.getLogger(table_suggetions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
             Logger.getLogger(Add_Records.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
             Logger.getLogger(Add_Records.class.getName()).log(Level.SEVERE, null, ex);
         } 
    }//GEN-LAST:event_TRYSAVEActionPerformed

    private void CLEAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEAR1ActionPerformed
       
    }//GEN-LAST:event_CLEAR1ActionPerformed

    private void CLEAR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEAR4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLEAR4ActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked

        DefaultTableModel modelz =  (DefaultTableModel)jTable.getModel() ;
        int selecIndex = jTable.getSelectedRow();

        
       search.setText("");
        students1.setSelectedItem(modelz.getValueAt(selecIndex, 0).toString() );
       
        //        jComboBox2.setSelectedItem(model2.getValueAt(selecIndex, 0).toString() );
    }//GEN-LAST:event_jTableMouseClicked

    private void students1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_students1MouseClicked

    }//GEN-LAST:event_students1MouseClicked

    private void students1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_students1KeyPressed

    }//GEN-LAST:event_students1KeyPressed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased

      LoadSearchData();
    }//GEN-LAST:event_searchKeyReleased

    private void goodmoral1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goodmoral1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_goodmoral1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR1;
    private javax.swing.JButton CLEAR4;
    private javax.swing.JTextField COMPLETION;
    private javax.swing.JTextField DIPLOMA;
    private javax.swing.JTextField DISMISSAL;
    private javax.swing.JTextField ENROLLMENT;
    private javax.swing.JTextField GOODMORAL;
    private javax.swing.JTabbedPane PSA;
    private javax.swing.JTextField PSA1;
    private javax.swing.JButton SAVE;
    private javax.swing.JTextField SF10;
    private javax.swing.JTextField SF9;
    private javax.swing.JButton TRYSAVE;
    private javax.swing.JButton completion;
    private javax.swing.JButton diploma;
    private javax.swing.JButton dismissal;
    private javax.swing.JButton enrollment;
    private javax.swing.JButton enrool;
    private javax.swing.JButton goodmoral1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JPanel panel;
    private javax.swing.JButton psa;
    private javax.swing.JComboBox schoolyr;
    public static javax.swing.JTextField search;
    private javax.swing.JButton sf10;
    private javax.swing.JButton sf9;
    private javax.swing.JComboBox students1;
    // End of variables declaration//GEN-END:variables
}
